### ISSUE TITLE
KMAC not recognizing --neg_seq option

### ISSUE THREAD

**Issue by le236** [gifford-lab/GEM3#1]
Hello,

I am trying to include a set of negative sequences in my KMAC run using the --neg_seq option, as in the command listed below:

`java -Xmx8G -jar gem.jar KMAC --pos_seq peaks_forkmac.fa --neg_seq background_peaks_forkmac.fa --k_win 500 --k_min 5 --k_max 13 --k_top 10 --out_name kmac_peaks_kwin500_kmin5_kmax13_vsbg`

However, it is not recognizing this file and is instead still using the default set of di-nucleotide shuffled sequences as negative sequences. The first several lines of the output are below:

```
KMAC motif discovery (version 1.3)

Options:
KMAC --pos_seq peaks_forkmac.fa --neg_seq background_peaks_forkmac.fa --k_win 500 --k_min 5 --k_max 13 --k_top 10 --out_name kmac_peaks_kwin500_kmin5_kmax13_vsbg

Loaded 36718 input positive sequences.
Use di-nucleotide shuffled sequences as negative sequences.
```
Am I using this option correctly? Thank you in advance for your help.

**Comment by yguoma** [comment]
Thank you for reporting the bug! I have fixed it. Please download a new version of gem.jar from http://groups.csail.mit.edu/cgs/gem/versions.html.
