### ISSUE TITLE
GC content of genome reported by GEM

### ISSUE THREAD

**Issue by gavrielm** [gifford-lab/GEM3#3]
Hello,
I am running GEM on my data and I have a question regarding a section of the standard output from the GEM job that I ran.

The relevant section is as follows:

Loading genome sequences ...
Done, 2.3m
GC content=0.41

Use di-nucleotide shuffled sequences as negative sequences.

Estimated GC content is 0.43. Set [--gc -1] to use the estimated GC content.
Provided  GC content is 0.41.

My questions:
1) When GEM says "GC content=0.41”, is GEM referring to the GC content across all the genome sequences I read in? If so, then that is an error because I know the GC content of the genome I work on is 0.56 (i.e. 56%).

2) When GEM uses di-nucleotide shuffled sequences as negative sequences, is it shuffling sequences across the whole genome? Are these shuffled sequences the same length as the positive sequences (i.e. 61 bp)? Is the "Estimated GC content is 0.43" line referring to the estimated GC content of the shuffled sequences?

Thank you very much,
Gavriel

**Comment by yguoma** [comment]
1. The default GC=0.41 is set for human genome. You could set --gc 0.56 for
your data. The estimated GC content is from estimated from the binding
event sequences, not from the whole genome.

2. It shuffles the positive sequences from the binding events. So, yes,
same length and same number as the positive sequences.

GEM uses KMAC for motif discovery. You may want to read the KSM/KMAC paper
if you are interested.
