### ISSUE TITLE
NullPointerException error message

### ISSUE THREAD

**Issue by gavrielm** [gifford-lab/GEM3#4]
Hello,
I received the following error message when I ran a GEM job:

		Exception in thread "main" java.lang.NullPointerException
			at edu.mit.csail.cgs.deepseq.discovery.KPPMixture.plotAllReadDistributions(KPPMixture.java:3248)
			at edu.mit.csail.cgs.deepseq.discovery.GEM.runMixtureModel(GEM.java:269)
			at edu.mit.csail.cgs.deepseq.discovery.GEM.main(GEM.java:345)
		

Does anyone know why I received this message? 

It is worth noting that I ran 3 GEM jobs and I received this error message for 2 of the jobs. These 2 jobs also produced warning messages that the read distribution was not updated because too few significant binding events were identified. These 2 jobs also did not generate a "Finished" message in the standard output; whereas, the 3rd job (the job without any error messages) did completely finish.

Thanks a lot,
Gavriel

**Comment by yguoma** [comment]
You are correct. You can set --min to a smaller value.
`--min [n]` 
minimum number of events called by GPS/GEM to learn a read distribution and continue the next round (default=500). Note: with less number of binding events, the read distribution might be more noisy. You can try increase --smooth parameter.

I also fixed the code to handle the error msg in Version 3.4, which will be released soon.
